on: push
name: Lint and Test
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: install
    - name: Lint
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: run lint
    - name: Test
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      env:
        GSR_TEST_GITHUB_PASSWORD: ${{ secrets.GSR_TEST_GITHUB_PASSWORD }}
        GSR_TEST_GITHUB_TOKEN: ${{ secrets.GSR_TEST_GITHUB_TOKEN }}
        GSR_TEST_GITHUB_USERNAME: ${{ secrets.GSR_TEST_GITHUB_USERNAME }}
      with:
        args: test
    - name: Master
      uses: actions/bin/filter@b2bea0749eed6beb495a8fa194c071847af60ea1
      with:
        args: branch master
    - name: Publish
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
